name: fermipy
channels:
  - fermi
  - plotly
  - conda-forge
  - defaults
  - cta-observatory
dependencies:
  - python
  - astropy
  - scipy
  - pandas
  - matplotlib
  - yaml
  - lxml
  - fermitools

